[default.extend-identifiers]
balatro = "balatro"
clippy = "clippy"
conv = "conv"
crossterm = "crossterm"
cursorvec = "cursorvec"
debuffed = "debuffed"
itertools = "itertools"
libc = "libc"
mult = "mult"
peekable = "peekable"
ratatui = "ratatui"
repr = "repr"
rustc = "rustc"
seekable = "seekable"
sigtstp = "sigtstp"