on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Choose major for API breaking changes, minor for functionality addition and patch for bugfixes or refactoring
        options:
          - major
          - minor
          - patch

name: Publish

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo release --workspace --sign ${{ inputs.release-type }} --execute
