on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Choose major for API breaking changes, minor for functionality addition and patch for bugfixes or refactoring
        options:
          - major
          - minor
          - patch

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}

      - uses: chainguard-dev/actions/setup-gitsign@main
      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-workspaces
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces

      - name: Update version
        run: |
          cargo workspaces version ${{ inputs.release-type }} \
            --yes \
            --message "[Bump] Update master version to v{{version}}"


      - name: Publish to crates.io
        run: |
          cargo workspaces publish prerelease \
            --yes \
            --all \
            --from-git \
            --token ${{ secrets.CARGO_TOKEN }} \
            --message "[Release] Release version v{{version}}! 🚀" \
