on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Choose major for API breaking changes, minor for functionality addition and patch for bugfixes or refactoring
        options:
          - major
          - minor
          - patch

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-workspaces
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces

      - name: Publish to crates.io
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "<>"

          cargo workspaces publish ${{ inputs.release-type }} \
            --yes \
            --all \
            --token ${{ secrets.CARGO_TOKEN }} \
            --message "[Release] Release version v%v! 🚀" \
